export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGOUT = 'LOGOUT';

export const CREATE_PROFILE_SUCCESS = 'CREATE_PROFILE_SUCCESS';
export const CREATE_PROFILE_ERROR = 'CREATE_PROFILE_ERROR';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_ERROR = 'GET_PROFILE_ERROR';
export const GET_SEEKER_PROFILE_SUCCESS = 'GET_SEEKER_PROFILE_SUCCESS';
export const GET_SEEKER_PROFILE_ERROR = 'GET_SEEKER_PROFILE_ERROR';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_ERROR = 'UPDATE_PROFILE_ERROR';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';

export const GET_ALL_POSTS = 'GET_ALL_POSTS';
export const GET_INDIVIDUAL_POST_SUCCESS = 'GET_INDIVIDUAL_POST_SUCCESS';
export const GET_INDIVIDUAL_POST_ERROR = 'GET_INDIVIDUAL_POST_ERROR';
export const UPDATE_COMMENTS = 'UPDATE_COMMENTS';
export const UPDATE_LIKES = 'UPDATE_LIKES';
export const UPDATE_SAVED_POSTS = 'UPDATE_SAVED_POSTS';
